#!/usr/bin/env python
"""Build the generated tables of the ML4PM 2027 draft from existing artifacts.

Scope of the current draft: setup only (no results). This script therefore
reads only data/processed/<dataset>/manifest.json (computed by
scripts/prepare_dataset.py in Phase 2) and writes the dataset-statistics
table into paper/ml4pm2027/generated/. It never trains, extracts, or
computes geometry, and never writes outside the paper folder (PLAN.md
Phase 11: "no hand-copied numbers into paper/").

Usage (from repo root):
    uv run python paper/ml4pm2027/scripts/make_assets.py
"""
from __future__ import annotations

import json
from pathlib import Path

PAPER_DIR = Path(__file__).resolve().parent.parent
REPO_ROOT = PAPER_DIR.parent.parent
GEN_DIR = PAPER_DIR / "generated"

DATASETS = ["helpdesk", "bpic12", "bpic17", "bpic19", "sepsis"]
DATASET_LABEL = {
    "helpdesk": "Helpdesk~\\cite{data_helpdesk}",
    "bpic12": "BPIC12~\\cite{data_bpic12}",
    "bpic17": "BPIC17~\\cite{data_bpic17}",
    "bpic19": "BPIC19$^\\dagger$~\\cite{data_bpic19}",
    "sepsis": "Sepsis~\\cite{data_sepsis}",
}


def thousands(n: int) -> str:
    return f"{n:,}".replace(",", "{,}")


def table_datasets() -> str:
    rows = []
    for ds in DATASETS:
        path = REPO_ROOT / "data" / "processed" / ds / "manifest.json"
        if not path.exists():
            raise FileNotFoundError(f"{path} missing - run scripts/prepare_dataset.py --all first")
        m = json.loads(path.read_text(encoding="utf-8"))
        s, sizes = m["stats"], m["split_sizes"]
        rows.append(
            f"{DATASET_LABEL[ds]} & {thousands(s['n_cases'])} & {thousands(s['n_events'])} & "
            f"{s['n_activities']} & {s['mean_trace_length']:.1f} & {s['median_trace_length']:.0f} & "
            f"{thousands(s['n_trace_variants'])} & {s['variant_entropy_bits']:.2f} & "
            f"{thousands(sizes['train'])}/{thousands(sizes['val'])}/{thousands(sizes['test'])} \\\\"
        )
    return "\n".join([
        "% Auto-generated by scripts/make_assets.py from data/processed/*/manifest.json -- do not edit.",
        "\\begin{tabular}{@{}lrrrrrrrr@{}}",
        "\\toprule",
        "Log & Cases & Events & $|\\mathcal{A}|$ & $\\bar{T}$ & $\\tilde{T}$ & Variants & "
        "$H_{\\mathrm{var}}$ & Train/val/test cases \\\\",
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
    ]) + "\n"


def main() -> None:
    GEN_DIR.mkdir(exist_ok=True)
    (GEN_DIR / "tab_datasets.tex").write_text(table_datasets(), encoding="utf-8")
    print("wrote", GEN_DIR / "tab_datasets.tex")


if __name__ == "__main__":
    main()
